#!/bin/sh

coffee --watch --join nova.js --compile ./src/require.coffee ./src/nova.coffee ./src/modules/*.coffee
uglifyjs --unsafe -nc --reserved-names "require" -o nova.min.js nova.js ./lib/superagent.js
